server:
  port: 8080

spring:
  application:
    name: tia-alibaba-chat
  ai:
    openai:
      api-key: <changeit>
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-max
