server:
  port: 8080

spring:
  application:
    name: tia-alibaba-embedding
  ai:
    openai:
      api-key: <changeit>
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      embedding:
        options:
          model: text-embedding-v1
    